### ISSUE TITLE
Use git hooks pre-commit , run ❌

### ISSUE THREAD

**Issue by chinanf-boy** [thlorenz/doctoc#150]
## I try many time

use `git commit -m "test"` in term

``` bash
doctoc................................................
...................Failed
hookid: doctoc
Files were modified by this hook. Additional output:

DocToccing single file "./readme.md" for github.com.

==================
"./readme.md" will be updated

Everything is OK.

DocToccing single file "readme.md" for github.com.
==================

"readme.md" will be updated

Everything is OK.
```

### config

``` yaml
#.pre-commit-config.yaml
repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v1.3.1  # substitute a tagged version
    hooks:
    -   id: doctoc
        args: ["./readme.md"]
```

## my step

1. `pre-commit` got, `doctoc` got, `pre-commit install` got
2. add readme.md some `h*`, use `git commit -m test` in Vscode , `cmd + Enter`

![image](https://user-images.githubusercontent.com/20272484/42360665-bd0c69ea-811c-11e8-9844-1f4126a55f47.png)

### you see the `readme.md` change ,but the `commit` no finish, just `stop` there 

---
