### ISSUE TITLE
doctoc pinned to 1.4.0 returns 2.0.0 for version

### ISSUE THREAD

**Issue by ricochet** [thlorenz/doctoc#190]
Was doctoc 1.4.0 re-published in npm with 2.0.0 content?

```bash
npm install -g doctoc@1.4.0
doctoc --version
2.0.0
```

**Comment by AndrewSouthpaw** [comment]
cc @thlorenz

**Comment by thlorenz** [comment]
I have no idea honestly I can't even remember that we have a `--version` flag.
But I'm pretty sure what's published as `1.4.0` did not get changed  as it is even impossible to do that (enforced by npm)

**Comment by ricochet** [comment]
I'm now on v2 so this is not a bug that's impacting me. FYI reporting 2.0.0 at 1.4.0 started to occur when 2.0.0 was released. I have unit tests that verify versions when building docker images. 

This is the test that started failing:
```yaml
  - name: "doctoc version test"
    command: "npm"
    args: ["show", "doctoc", "version"]
    expectedOutput: ["1.4.0"]
```
